project:
  type: website
  output-dir: docs

website:
  title: "ICCB - Open Source Geospatial Tools for Conservation under Climate Change"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

