project:
  type: website
  output-dir: docs

website:
  title: "ICCB - Open Geospatial Tools"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Session 1/session_1_home.qmd
        text: Session 1
      - href: Session 2/session_2_home.qmd
        text: Session 2
      - href: Session 3/session_3_home.qmd
        text: Session 3
      - href: Session 4/session_4_home.qmd
        text: Session 4
      - href: Session 5/session_5_home.qmd
        text: Session 5
      - about.qmd
      
    right:
      - icon: github
        href: https://github.com/geospatial-community/ICCB_geospatial_tools_conservation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

