project:
  type: website
  output-dir: docs
  resources:
    - "*.pdf"
    
execute:
  freeze: auto

website:
  title: "ICCB - Open Geospatial Tools"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: workshop_overview.qmd
        text: Overview
      # - href: Session 1/session_1_home.qmd
      - href: Session 1/session_1_code.qmd
        text: Session 1
      - href: Session 2/session_2_home.qmd
        text: Session 2
      - href: Session 3/session_3_home.qmd
        text: Session 3
      - href: Session 4/session_4_home.qmd
        text: Session 4
      - href: Session 5/session_5_home.qmd
        text: Session 5
      - about.qmd
      
    right:
    - icon: github
      href: https://github.com/geospatial-community/ICCB_geospatial_tools_conservation

    
  sidebar:
    
    - title: "Session 1"
      contents: 
        # - Session 1/session_1_home.qmd
        - Session 1/session_1_code.qmd
        
    - title: "Session 2"
      contents: 
        - Session 2/session_2_home.qmd
        - Session 2/session_2_code.qmd
        
    - title: "Session 3"
      contents: 
        - Session 3/session_3_home.qmd
        # - Session 3/ICCB_Species_data.qmd
        # - Session 3/ICCB_Environmental_data.qmd
        - Session 3/ICCB_Modelling_and_validation.qmd
        
    - title: "Session 4"
      contents: 
        - Session 4/session_4_home.qmd
        
    - title: "Session 5"
      contents: 
        - Session 5/session_5_home.qmd
    
    
  page-footer:
    background: light
    center:
      - icon: github
        href: https://github.com/geospatial-community/ICCB_geospatial_tools_conservation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

